<?php

/*
 * Implements hook_secure_permissions
 *
 * Adding permissions for video hero unit bean
 */
function cu_video_hero_unit_bundle_secure_permissions($role) {
  $permissions = array(
    'anonymous user' => array(
      'view any video_hero_unit bean',
    ),
    'authenticated user' => array(
      'view any video_hero_unit bean',
    ),
    'administrator' => array(
      'create any video_hero_unit bean',
      'delete any video_hero_unit bean',
      'edit any video_hero_unit bean',
      'view any video_hero_unit bean',
    ),
    'developer' => array(
      'create any video_hero_unit bean',
      'delete any video_hero_unit bean',
      'edit any video_hero_unit bean',
      'view any video_hero_unit bean',
    ),
    'edit_my_content' => array(
      'view any video_hero_unit bean',
    ),
    'edit_only' => array(
      'edit any video_hero_unit bean',
      'view any video_hero_unit bean',
    ),
    'site_editor' => array(
      'create any video_hero_unit bean',
      'delete any video_hero_unit bean',
      'edit any video_hero_unit bean',
      'view any video_hero_unit bean',
    ),
    'site_owner' => array(
      'create any video_hero_unit bean',
      'delete any video_hero_unit bean',
      'edit any video_hero_unit bean',
      'view any video_hero_unit bean',
    ),
  );

  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}
