<?php

/**
 *
 * Implements hook_shortcode_info
 */
function cu_livestream_embed_shortcode_info() {
  $shortcodes = array();
  $shortcodes['livestream'] = array(
    'title' => t('livestream Embed'),
    'description' => t('Embed content from livestream.com'),
    'process callback' => 'cu_livestream_embed_livestream_embed',
    'tips callback' => 'cu_livestream_embed_livestream_tips',
    'default settings' => array(),
  );
  return $shortcodes;
}
/*
 * Process callback for cu_livestream_embed_shortcode_info
 */
function cu_livestream_embed_livestream_embed($attrs, $content = NULL) {
  extract(shortcode_attrs(array(
    'id' => '',
    'account' => '',
    'event' => '',
  ), $attrs));
  $output = '<iframe id="' . $id . '" src="//livestream.com/accounts/' . $account . '/events/' . $event . '/player?width=560&height=315&autoPlay=true&mute=false" width="100%" height="315" frameborder="0" scrolling="no" allowfullscreen></iframe>
<script type="text/javascript" data-embed_id="' . $id . '" src="//livestream.com/assets/plugins/referrer_tracking.js"></script>';
  return $output;
}
/*
 * Tips callback for cu_livestream_embed_shortcode_info
 */
function cu_livestream_embed_livestream_tips($format, $long) {
  $output = '[livestream id="Embed code ID" account="Embed code Account" event="Embed code Event" /]';
  return $output;
}

/**
 * Implements hook_filter_info_alter().
 */
function cu_livestream_embed_filter_info_alter(&$info) {
  // Load the wysiwyg text format
  $format = filter_format_load('wysiwyg');
  // Get the filters on the wysiwyg text format
  $filters = filter_list_format($format->format);
  // Enable livestream shortcode
  $filters['shortcode']->settings['livestream'] = 1;
}
