<?php

/**
 * @file
 * Contains embed type definition for et_slate_form_block module.
 */

/**
 * Implements hook_embed_templates_types().
 *
 * @return array
 *   List of custom embed types.
 */
function et_slate_form_block_embed_templates_types() {
  $custom_types = array();
  $module_path = drupal_get_path('module', 'et_slate_form');
  $default_status = 'unpublished';

  $custom_types['et_slate_form_block'] = array(
    'label' => 'Slate Form Block',
    'form_callback' => 'et_slate_form_options',
    'submission_callback' => NULL,
    'renderer' => 'block',
    'default_status' => $default_status,
    'path' => $module_path,
    'template' => 'templates/slate-form',
  );

  return $custom_types;
}
