<?php

/**
 * Implements hook_menu().
 */
function cu_custom_logo_menu() {
  $items['admin/config/user-interface/custom-logo'] = array(
    'title' => 'Custom Logo',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cu_custom_logo_upload_form'),
    'access arguments' => array('administer themes'),
    'weight' => 8,
    'description' => 'Upload custom logos.',
  );
  return $items;
}

function cu_custom_logo_upload_form($form, &$form_state) {
  $form['instructions'] = array(
    '#type' => 'markup',
    '#markup' => '<p>Add logo images suitable for light and dark backgrounds. Both images are required for the logo to display.</p>',
  );
  $form['custom_white_logo'] = array(
    '#type' => 'managed_file',
    '#name' => 'custom_white_logo',
    '#title' => t('White logo (deprecated)'),
    '#size' => 40,
    '#description' => t('Image should be a transparent png which will be displayed on a dark background. Width should be fewer than 440 pixels. (This field will be removed in a future update).'),
    '#upload_location' => 'public://custom_logo/',
    '#default_value' => variable_get('custom_white_logo', ''),
  );
  $form['custom_black_logo'] = array(
    '#type' => 'managed_file',
    '#name' => 'custom_black_logo',
    '#title' => t('Black logo (deprecated)'),
    '#size' => 40,
    '#description' => t('Image should be a transparent png which will be displayed on a light background. Width should be fewer than 440 pixels. (This field will be removed in a future update).'),
    '#upload_location' => 'public://custom_logo/',
    '#default_value' => variable_get('custom_black_logo', ''),
  );

  $form['cu_custom_white_logo'] = array(
    '#type' => 'managed_file',
    '#name' => 'custom_white_logo',
    '#title' => t('White logo'),
    '#size' => 40,
    '#description' => t('Image should be a transparent png which will be displayed on a dark background. Width should be fewer than 440 pixels.'),
    '#upload_location' => 'public://custom_logo/',
    '#default_value' => variable_get('cu_custom_white_logo', ''),
  );

  $form['cu_custom_black_logo'] = array(
    '#type' => 'managed_file',
    '#name' => 'custom_black_logo',
    '#title' => t('Black logo'),
    '#size' => 40,
    '#description' => t('Image should be a transparent png which will be displayed on a light background. Width should be fewer than 440 pixels.'),
    '#upload_location' => 'public://custom_logo/',
    '#default_value' => variable_get('cu_custom_black_logo', ''),
  );

  $form['custom_logo_retina'] = array(
    '#type' => 'checkbox',
    '#name' => 'custom_logo_retina',
    '#title' => 'Retina Images',
    '#description' => 'Display as retina images.',
    '#default_value' => variable_get('custom_logo_retina', 0),
  );
  //$form = system_settings_form($form);
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  $form['#submit'][] = 'cu_custom_logo_upload_form_submit';
  return $form;
}

function cu_custom_logo_upload_form_submit($form, &$form_state) {
  // Original Logo Fields
  // White logo remove.
  if ($form_state['values']['custom_white_logo'] == 0 || $form_state['values']['custom_white_logo'] == 'remove') {
    $white_file = variable_get('custom_white_logo', FALSE);
    if ($white_file) {
      $white_file = file_load($white_file);
      file_delete($white_file, TRUE);
      variable_del('custom_white_logo');
    }
  }
  // White logo upload.
  elseif (isset($form_state['values']['custom_white_logo'])) {
    $white_file = file_load($form_state['values']['custom_white_logo']);
    $white_file->status = FILE_STATUS_PERMANENT;
    file_save($white_file);
    file_usage_add($white_file, 'cu_custom_logo', 'white_logo', 1, 1);
    variable_set('custom_white_logo', $form_state['values']['custom_white_logo']);
  }

  // Black logo remove.
  if ($form_state['values']['custom_black_logo'] == 0 || $form_state['values']['custom_black_logo'] == 'remove') {
    $black_file = variable_get('custom_black_logo', FALSE);
    if ($black_file) {
      $black_file = file_load($black_file);
      file_delete($black_file, TRUE);
      variable_del('custom_black_logo');
    }
  }
  // Black logo upload.
  elseif (isset($form_state['values']['custom_black_logo'])) {
    $black_file = file_load($form_state['values']['custom_black_logo']);
    $black_file->status = FILE_STATUS_PERMANENT;
    file_save($black_file);
    file_usage_add($black_file, 'cu_custom_logo', 'black_logo', 1, 1);
    variable_set('custom_black_logo', $form_state['values']['custom_black_logo']);
  }


  // New 2019 Logo Fields
  // White logo remove.
  if ($form_state['values']['cu_custom_white_logo'] == 0 || $form_state['values']['cu_custom_white_logo'] == 'remove') {
    $white_file = variable_get('cu_custom_white_logo', FALSE);
    if ($white_file) {
      $white_file = file_load($white_file);
      file_delete($white_file, TRUE);
      variable_del('cu_custom_white_logo');
    }
  }
  // White logo upload.
  elseif (isset($form_state['values']['cu_custom_white_logo'])) {
    $white_file = file_load($form_state['values']['cu_custom_white_logo']);
    $white_file->status = FILE_STATUS_PERMANENT;
    file_save($white_file);
    file_usage_add($white_file, 'cu_custom_logo', 'cu_custom_white_logo', 1, 1);
    variable_set('cu_custom_white_logo', $form_state['values']['cu_custom_white_logo']);
  }

  // Black logo remove.
  if ($form_state['values']['cu_custom_black_logo'] == 0 || $form_state['values']['cu_custom_black_logo'] == 'remove') {
    $black_file = variable_get('cu_custom_black_logo', FALSE);
    if ($black_file) {
      $black_file = file_load($black_file);
      file_delete($black_file, TRUE);
      variable_del('cu_custom_black_logo');
    }
  }
  // Black logo upload.
  elseif (isset($form_state['values']['cu_custom_black_logo'])) {
    $black_file = file_load($form_state['values']['cu_custom_black_logo']);
    $black_file->status = FILE_STATUS_PERMANENT;
    file_save($black_file);
    file_usage_add($black_file, 'cu_custom_logo', 'cu_custom_black_logo', 1, 1);
    variable_set('cu_custom_black_logo', $form_state['values']['cu_custom_black_logo']);
  }


  variable_set('custom_logo_retina', $form_state['values']['custom_logo_retina']);
}

function cu_custom_logo_page_alter(&$page) {
  // Get retina settings
  $retina = variable_get('custom_logo_retina', 0);
  // Load logo file to get dimensions
  if ($retina) {
    if ($file = variable_get('custom_white_logo', NULL)) {
      $file = variable_get('custom_white_logo', NULL);
      $custom_logo = file_load($file);
      $logo_info = image_get_info($custom_logo->uri);
      $logo_width = $retina ? $logo_info['width']/2 : $logo_info['width'];
      drupal_add_css('img.custom-logo {max-width:' . $logo_width . 'px !important; width:100%; margin-right:20px;}', array('type' => 'inline'));
    }
  }
  // New logos should all be retina ready.
  if ($file = variable_get('cu_custom_white_logo', NULL)) {
    $custom_logo = file_load($file);
    $logo_info = image_get_info($custom_logo->uri);
    $logo_width = $logo_info['width']/2;
    drupal_add_css('img.cu-custom-logo {max-width:' . $logo_width . 'px !important; width:100%; margin-right:20px;}', array('type' => 'inline'));
  }
}
