<?php

/**
 * @file
 * Drupal hooks for et_linkedin module.
 */

/**
 * Callback to generate form components for LinkedIn embed type.
 *
 * @param array $form
 *   Form containing default embed template form options.
 * @param array $form_state
 *   State of the default embed template form.
 * @param int|null $id
 *   ID of the current embed being edited if that embed exists.
 * @param array $data
 *   Data of the current embed if it is being edited.
 */
function cu_doubleclick_form_options(&$form, &$form_state, $id = NULL, $data = array()) {

  $size = variable_get('et_form_field_size', 128);

  $form['options'] = array(
    '#type' => 'fieldset',
    '#title' => t('Embed Data'),
    '#weight' => -10,
  );

  $form['options']['account_id'] = array(
    '#title' => t('ID'),
    '#description' => t('Your Campaign ID.'),
    '#type' => 'textfield',
    '#default_value' => !empty($data['account_id']) ? $data['account_id'] : '',
    '#required' => TRUE,
    '#size' => $size,
  );

  $form['options']['activity'] = array(
    '#title' => t('Activity'),
    '#description' => t('Activity name of this tag.'),
    '#type' => 'textfield',
    '#default_value' => !empty($data['activity']) ? $data['activity'] : '',
    '#size' => $size,
  );

  $form['options']['creation'] = array(
    '#title' => t('Creation Date'),
    '#description' => t('Creation date of this campaign.'),
    '#type' => 'textfield',
    '#default_value' => !empty($data['creation']) ? $data['creation'] : '',
    '#size' => $size,
  );

  $form['options']['page_location'] = array(
    '#title' => t('Location'),
    '#description' => t('URL where tracking pixel will be added.'),
    '#type' => 'textfield',
    '#default_value' => !empty($data['page_location']) ? $data['page_location'] : '',
    '#size' => $size,
  );

  $form['options']['type'] = array(
    '#title' => t('Type'),
    '#description' => t('Type of campaign.'),
    '#type' => 'textfield',
    '#default_value' => !empty($data['type']) ? $data['type'] : '',
    '#size' => $size,
  );

  $form['options']['category'] = array(
    '#title' => t('Category'),
    '#description' => t('Category of campaign.'),
    '#type' => 'textfield',
    '#default_value' => !empty($data['category']) ? $data['category'] : '',
    '#size' => $size,
  );

  $position_options = array(
    'top' => 'Top',
    'bottom' => 'Bottom',
  );

  $form['options']['position'] = array(
    '#title' => t('Location'),
    '#type' => 'select',
    '#options' => $position_options,
    '#description' => t('Choose where on the page the embed is placed. Look at the embed code instructions to determine where it should be placed.'),
    '#default_value' => !empty($data['position']) ? $data['position'] : 0,
  );
}

/**
 * Implements hook_embed_templates_types().
 *
 * @return array
 *   List of custom embed types.
 */
function cu_doubleclick_embed_templates_types() {
  $custom_types = array();
  $module_path = drupal_get_path('module', 'cu_doubleclick');
  $default_status = 'unpublished';

  $custom_types['cu_doubleclick'] = array(
    'label' => 'Doubleclick Floodlight Tag Test',
    'form_callback' => 'cu_doubleclick_form_options',
    'submission_callback' => NULL,
    'renderer' => 'page_top_bottom',
    'default_status' => $default_status,
    'path' => $module_path,
    'template' => 'templates/cu-doubleclick',
  );

  return $custom_types;
}
