<?php

/*
 * Implements hook_secure_permissions
 *
 * Adding permissions for video reveal bean
 */
function cu_publications_bundle_secure_permissions($role) {
  $permissions = array(
    'anonymous user' => array(
    ),
    'authenticated user' => array(
    ),
    'administrator' => array(
      'create issue content',
      'delete any issue content',
      'delete own issue content',
      'edit any issue content',
      'edit own issue content',
      'view any issue content',
    ),
    'developer' => array(
      'create issue content',
      'delete any issue content',
      'delete own issue content',
      'edit any issue content',
      'edit own issue content',
      'view any issue content',
    ),
    'edit_my_content' => array(
      'edit own issue content',
      'view any issue content',
    ),
    'edit_only' => array(
      'edit any issue content',
      'edit own issue content',
      'view any issue content',
    ),
    'site_editor' => array(
      'create issue content',
      'delete any issue content',
      'delete own issue content',
      'edit any issue content',
      'edit own issue content',
      'view any issue content',
    ),
    'site_owner' => array(
      'create issue content',
      'delete any issue content',
      'delete own issue content',
      'edit any issue content',
      'edit own issue content',
      'view any issue content',
    ),
  );

  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}
